export default [
  {
    id: 'bio-plant-mass',
    subject: 'biology',
    topic: 'Photosynthesis',
    difficulty: 1,
    objective: 'The student can explain that most of a plant\'s mass comes from carbon dioxide in the air, fixed through photosynthesis.',
    claim: 'Plants get most of their mass from the soil.',
    scaffold: 'If a tree grows from a seed into tons of wood, does a hole appear in the ground around it?',
    concepts: [
      {
        id: 'soil_unchanged',
        label: 'Soil mass barely changes',
        description: 'Experiments (van Helmont\'s willow) show soil loses only a tiny amount of mass while the plant gains a lot.',
        patterns: [/soil.{0,40}(barely|hardly|doesn'?t|does not|same|little|tiny|small|not much|wouldn'?t)/, /(hole|pit|less soil|soil (would )?(shrink|disappear|decrease))/, /van helmont|willow/, /weigh(ed|ing)? the soil/],
        followUp: 'If that were true, what should happen to the mass of the soil after a plant grows?',
      },
      {
        id: 'co2_air',
        label: 'Mass comes from CO₂ in the air',
        description: 'Plants take in carbon dioxide from the air; the carbon becomes most of their dry mass.',
        patterns: [/carbon dioxide|\bco2\b|co₂/, /(from|out of|in) the air/, /atmospher/, /\bcarbon\b/],
        followUp: 'If not the soil, where could all that material come from? What do leaves take in?',
      },
      {
        id: 'photosynthesis',
        label: 'Photosynthesis builds sugars',
        description: 'Photosynthesis uses light energy to combine CO₂ and water into glucose, which builds cellulose and other tissue.',
        patterns: [/photosynth/, /glucose|sugar|cellulose|starch/, /light energy|sunlight/],
        followUp: 'What process turns that raw material into the stuff a plant is made of?',
      },
    ],
    clue: 'soil_unchanged',
    misconceptions: [
      {
        id: 'nutrients_mass',
        label: 'Thinking nutrients from soil make up the mass',
        patterns: [/(absorb|take|get|comes?|from).{0,25}(soil|nutrients|minerals|dirt).{0,25}(mass|weight|grow|build|body)/, /nutrients (make|give|are) (up )?(the |most )?(mass|weight)/],
        correction: 'Soil minerals are essential but make up only a tiny fraction of a plant\'s mass. The bulk is carbon from the air.',
        socratic: 'If the soil were feeding the plant\'s mass, what would you measure in the pot after years of growth?',
      },
      {
        id: 'from_water_only',
        label: 'Thinking water alone provides the mass',
        patterns: [/(all|most|mainly) (of )?(its|the) mass (comes )?from water/, /mass (comes )?(only|mainly|mostly) from water/],
        correction: 'Water contributes hydrogen and oxygen, and plants hold a lot of it, but the dry mass is mostly carbon, which comes from CO₂.',
        socratic: 'If you completely dried a tree, what would be left, and does water contain any carbon?',
      },
    ],
    counter: {
      text: 'But farmers add fertilizer to the soil and plants grow bigger. So the soil must be the source of their mass.',
      defense: {
        label: 'Fertilizer enables growth, it does not supply mass',
        description: 'Fertilizer provides small amounts of nutrients (nitrogen, phosphorus) that the plant needs to build proteins and run photosynthesis. Like vitamins, they enable growth but supply only a tiny fraction of the mass.',
        patterns: [/(nutrient|nitrogen|phosph|mineral|fertili[sz]er).{0,40}(small|tiny|little|enable|help|needed|allow|required|catalyst|not (the )?(mass|source))/, /vitamin/, /enable|allow/, /small (amount|fraction|percent|part)/, /help(s)? (it |the plant )?(grow|photosynth)/],
      },
      followUp: 'How much fertilizer do farmers add compared to the mass of the crop? What is it actually for?',
    },
    evidenceExamples: ['Van Helmont grew a willow for 5 years: it gained ~74 kg while the soil lost only ~57 g.'],
    acceptableReasoning: 'Soil mass barely changes; plants take CO₂ from air; photosynthesis converts CO₂ + water into sugars that build tissue; minerals are a tiny fraction.',
    hints: [
      'Think about what would happen to the pot if the claim were true.',
      'A famous experiment weighed the soil before and after a tree grew for years.',
      'Leaves take in a gas from the air. Which one contains carbon?',
      'Plants build most of their mass from CO₂ in the air through photosynthesis; the soil barely loses mass.',
    ],
    solution: {
      summary: 'Most plant mass comes from CO₂ in the air, turned into sugars by photosynthesis.',
      explanation: 'Van Helmont\'s willow gained ~74 kg while the soil lost only grams. Plants absorb CO₂ and use light energy to combine it with water into glucose, which builds cellulose. Soil minerals are essential but tiny in mass.',
    },
    keywords: ['plant', 'mass', 'soil', 'grow', 'tree', 'weight', 'nutrients', 'water'],
  },
  {
    id: 'bio-antibiotics',
    subject: 'biology',
    topic: 'Viruses vs bacteria',
    difficulty: 2,
    objective: 'The student can explain why antibiotics work on bacteria but not viruses.',
    claim: 'Antibiotics are a good treatment for the flu.',
    scaffold: 'What kind of germ causes the flu? What do antibiotics attack?',
    concepts: [
      {
        id: 'flu_virus',
        label: 'The flu is caused by a virus',
        description: 'Influenza is a virus, not a bacterium.',
        patterns: [/virus|viral|influenza/],
        followUp: 'What kind of pathogen causes the flu?',
      },
      {
        id: 'antibiotic_target',
        label: 'Antibiotics target bacterial structures',
        description: 'Antibiotics attack structures and processes specific to bacteria (cell walls, bacterial ribosomes). Viruses lack these and replicate inside our own cells.',
        patterns: [/bacteri/, /cell wall/, /ribosome/, /(inside|within) (our|human|host) cells/, /(don'?t|do not|doesn'?t|does not) have (cells|a cell|cell walls)/, /not (a )?(living )?cell/],
        followUp: 'What do antibiotics actually attack, and does a virus have that?',
      },
    ],
    clue: 'flu_virus',
    misconceptions: [
      {
        id: 'kills_all_germs',
        label: 'Thinking antibiotics kill all germs',
        patterns: [/antibiotics? (kill|work on|treat|fight)s? (all |any )?(germs|virus|viruses|everything|infections)/, /(any|all) (germs|infections)/],
        correction: 'Antibiotics only work against bacteria. They have no effect on viruses like influenza.',
        socratic: 'Why might a drug designed to break bacterial cell walls fail against something that has no cell wall at all?',
      },
    ],
    counter: {
      text: 'Doctors sometimes prescribe antibiotics to flu patients, though. So they must work on the flu.',
      defense: {
        label: 'Secondary bacterial infections and resistance',
        description: 'Doctors may prescribe antibiotics for a secondary bacterial infection (like pneumonia) that develops on top of the flu. Overprescribing also happens and drives antibiotic resistance.',
        patterns: [/secondary/, /pneumonia|complication/, /(bacterial )?infection (on top|as well|too|after)/, /resistan/, /over.?prescri/, /(mistake|misuse|pressure)/, /treat(s|ing)? (a |the )?(other|different|second)/],
      },
      followUp: 'What else might a doctor be treating? What happens when antibiotics are overused?',
    },
    evidenceExamples: ['Antibiotic resistance rises when antibiotics are prescribed for viral infections like colds and flu.'],
    acceptableReasoning: 'Flu = virus; antibiotics target bacteria-specific structures; viruses lack them; prescriptions may target secondary bacterial infection; misuse causes resistance.',
    hints: [
      'Not all germs are the same kind.',
      'The flu is caused by a specific kind of pathogen. Which kind?',
      'Antibiotics attack parts that only bacteria have.',
      'The flu is a virus. Antibiotics target bacterial structures like cell walls, which viruses do not have.',
    ],
    solution: {
      summary: 'Antibiotics kill bacteria; the flu is a virus, so antibiotics do not treat it.',
      explanation: 'Antibiotics target bacteria-specific structures such as cell walls and bacterial ribosomes. Influenza is a virus that replicates inside our cells and has none of these. Doctors may prescribe them for secondary bacterial infections; misuse drives resistance.',
    },
    keywords: ['antibiotics', 'flu', 'treatment', 'medicine', 'sick', 'germs', 'doctor'],
  },
  {
    id: 'bio-giraffe-evolution',
    subject: 'biology',
    topic: 'Natural selection',
    difficulty: 3,
    objective: 'The student can explain evolution by natural selection acting on inherited variation, and why acquired traits are not inherited.',
    claim: 'Giraffes got long necks because each giraffe stretched its neck to reach leaves and passed that longer neck on to its babies.',
    scaffold: 'If you build muscles at the gym, will your future children be born stronger?',
    concepts: [
      {
        id: 'variation',
        label: 'Natural variation exists',
        description: 'Giraffes are born with slightly different neck lengths due to genetic variation/mutation.',
        patterns: [/variation|vari(ed|ety|es)/, /(some|certain) (giraffes )?(were |are )?born with/, /mutation/, /(differ|different) (lengths?|necks?|sizes?)/, /naturally (longer|longer necks)/],
        followUp: 'Were all giraffes born with exactly the same neck length?',
      },
      {
        id: 'selection',
        label: 'Natural selection favors useful traits',
        description: 'Giraffes with longer necks reached more food, survived and reproduced more, so the trait became common over generations.',
        patterns: [/natural selection/, /surviv/, /reproduc|more (offspring|babies)/, /advantage/, /fitt?e(r|st)/, /selected/, /over (many )?generations/],
        followUp: 'Which giraffes would be more likely to survive and have babies in a food shortage?',
      },
      {
        id: 'acquired_not_inherited',
        label: 'Acquired traits are not inherited',
        description: 'Changes made during an individual\'s life (like stretching) do not change the genes passed to offspring.',
        patterns: [/genes?|genetic|dna/, /(not|isn'?t|aren'?t|can'?t|cannot) (be )?(passed|inherited)/, /acquired (traits|characteristics)/, /lamarck/],
        followUp: 'Can stretching during your lifetime change the DNA you pass on?',
      },
    ],
    clue: 'acquired_not_inherited',
    misconceptions: [
      {
        id: 'lamarckian',
        label: 'Thinking traits gained during life are inherited',
        patterns: [/stretch.{0,40}(pass|inherit)/, /(they|giraffes) (needed|wanted|tried) (to )?(longer|grow|reach)/, /(use|using) it.{0,20}(pass|inherit)/],
        correction: 'That is Lamarck\'s idea, which was disproven. Traits acquired during life do not alter the genes in eggs or sperm.',
        socratic: 'If a giraffe lost part of its tail in an accident, would its babies be born with shorter tails? Why not?',
      },
    ],
    counter: {
      text: 'But a bodybuilder\'s kids are often strong. Doesn\'t that prove acquired traits get inherited?',
      defense: {
        label: 'Shared genes and environment, not acquired muscle',
        description: 'The kids share genes for body type and often share the environment (diet, training habits). The muscles built at the gym are not encoded in sperm or egg cells.',
        patterns: [/genes|genetic|dna/, /environment|diet|train|lifestyle|habit|raised/, /correlat/, /(sperm|egg|gamete|germ.?line)/, /(born|naturally) (strong|athletic)/],
      },
      followUp: 'What else do the parent and kids share besides muscles built at the gym?',
    },
    evidenceExamples: ['Weismann cut the tails off mice for generations; their offspring were still born with normal tails.'],
    acceptableReasoning: 'Variation in neck length is inherited; longer-necked giraffes survived/reproduced more; over generations the trait spread; acquired changes do not alter genes.',
    hints: [
      'Think about whether changes made during a lifetime can reach the next generation.',
      'Were all giraffes originally identical, or were some born different?',
      'Which giraffes would survive a drought when low leaves run out?',
      'Natural selection: giraffes naturally varied in neck length; longer-necked ones survived and reproduced more, passing on their genes. Stretching does not change genes.',
    ],
    solution: {
      summary: 'Evolution works by natural selection on inherited variation; traits acquired during life are not inherited.',
      explanation: 'Giraffes varied genetically in neck length. When food was scarce, longer-necked individuals reached more leaves, survived and had more offspring, so the genes for long necks spread over generations. Stretching does not change DNA.',
    },
    keywords: ['giraffe', 'neck', 'stretch', 'babies', 'evolution', 'long', 'passed', 'leaves'],
  },
  {
    id: 'bio-controlled-experiment',
    subject: 'biology',
    topic: 'Experimental design',
    difficulty: 4,
    objective: 'The student can identify confounding variables and explain what makes an experiment a fair test.',
    claim: 'I watered one plant with coffee and it grew taller than my other plant, which was in a different room. So coffee makes plants grow.',
    scaffold: 'List every difference between the two plants, not just the coffee.',
    concepts: [
      {
        id: 'confounding',
        label: 'Other variables differ (confounding)',
        description: 'The plants were in different rooms, so light, temperature, and humidity also differed. Any of them could explain the result.',
        patterns: [/(different|another|other) room/, /\blight|sun/, /temperature|heat|warm/, /humid/, /confound/, /(other|another|extra) (variable|factor|difference)/],
        followUp: 'Besides coffee, what else was different between the two plants?',
      },
      {
        id: 'control',
        label: 'Change only one variable (fair test)',
        description: 'A fair test changes only the variable being studied and keeps everything else the same, with a control group.',
        patterns: [/control(led)? (group|experiment|variable|plant)/, /same (conditions|room|environment|light)/, /only (one|1) (variable|thing|difference|factor)/, /fair test/, /isolat/, /keep everything (else )?the same/],
        followUp: 'How would you design the test so coffee is the only difference?',
      },
    ],
    clue: 'confounding',
    misconceptions: [
      {
        id: 'single_result_proves',
        label: 'Thinking one result proves a cause',
        patterns: [/(this )?(proves|proven|proof)/, /coffee (has|contains) (nutrients|caffeine|nitrogen) so/],
        correction: 'One comparison cannot prove a cause, especially when other factors differ.',
        socratic: 'If you flipped a coin once and got heads, would that prove the coin always lands heads?',
      },
    ],
    counter: {
      text: 'Fine, I\'ll put both plants in the same room. Now if the coffee plant grows taller, it\'s proven.',
      defense: {
        label: 'One plant each is too small a sample',
        description: 'With one plant per group, natural variation between individual plants could explain the result. Use many plants, repeat the experiment, and analyze statistically. Results "support" rather than "prove".',
        patterns: [/sample/, /(one|single|1) plant/, /(more|many|several) plants/, /repeat|replicat/, /chance|random|luck|fluke/, /individual (differences|variation)/, /genetic/, /statistic/, /not (prove|proof)|support|suggest/],
      },
      followUp: 'Could two plants differ in height even if you treated them identically?',
    },
    requireEvidence: false,
    evidenceExamples: ['Two plants from the same seed packet, in identical conditions, can differ in height by several centimeters.'],
    acceptableReasoning: 'Different rooms introduce confounding variables (light, temperature); fair tests change one variable with a control; larger samples and repetition needed.',
    hints: [
      'Coffee is not the only difference between the plants.',
      'What might differ between two rooms?',
      'Scientists try to change only one thing at a time.',
      'Light, temperature and other conditions differed between rooms (confounding variables). A fair test keeps everything the same except coffee, using a control group and many plants.',
    ],
    solution: {
      summary: 'A fair experiment changes one variable, controls the rest, and uses enough samples.',
      explanation: 'The plants differed in room (light, temperature, humidity), so those confounding variables could explain the growth. A fair test puts many plants in identical conditions, changes only the watering, and repeats the experiment.',
    },
    keywords: ['coffee', 'plant', 'grew', 'taller', 'room', 'experiment', 'water'],
  },
];
