export default [
  {
    id: 'eco-elasticity',
    subject: 'economics',
    topic: 'Price elasticity',
    difficulty: 1,
    objective: 'The student can explain how price elasticity of demand affects total revenue.',
    claim: 'Increasing prices will always increase a company\'s revenue.',
    scaffold: 'Revenue = price × quantity sold. What happens to the second part?',
    concepts: [
      {
        id: 'quantity_falls',
        label: 'Higher prices reduce quantity sold',
        description: 'When price rises, customers usually buy less, so quantity sold falls.',
        patterns: [/(demand|people|customers|buyers|sales|quantity|units).{0,30}(fall|drop|decreas|less|fewer|lower|down|stop|switch|leave)/, /(buy|purchase|sell)s? (less|fewer)/, /fewer (people|customers|units|sales)/, /(go|switch) to (a )?(competitor|cheaper|substitute)/],
        followUp: 'Revenue is price times quantity. When the price goes up, what happens to the quantity people buy?',
      },
      {
        id: 'elasticity',
        label: 'Price elasticity of demand',
        description: 'Elasticity measures how sensitive quantity demanded is to price. If demand is elastic, the percentage fall in quantity outweighs the price rise and revenue drops.',
        patterns: [/elastic/, /(sensitive|responsive|sensitivity) to (the )?price/, /substitut/, /percent(age)?.{0,30}(more|bigger|larger|outweigh)/],
        followUp: 'What economic concept describes how strongly buyers react to a price change?',
      },
    ],
    clue: 'quantity_falls',
    misconceptions: [
      {
        id: 'revenue_is_profit',
        label: 'Confusing revenue with profit',
        patterns: [/revenue (is|means|equals|=) (the )?profit/, /same (thing )?as profit/],
        correction: 'Revenue is total money coming in (price × quantity). Profit is revenue minus costs. The claim is about revenue.',
        socratic: 'Is revenue the money left after costs, or all the money that comes in from sales? Which one is the claim about?',
      },
      {
        id: 'demand_fixed',
        label: 'Assuming people keep buying the same amount',
        patterns: [/(people|customers) (will )?(always|still) buy (the same|it)/, /demand (doesn'?t|does not|won'?t|will not) change/],
        correction: 'For most goods, people buy less when the price rises. How much less is the key question.',
        socratic: 'If your favorite snack doubled in price tomorrow, would you buy exactly as many as before? Would everyone?',
      },
    ],
    counter: {
      text: 'But luxury brands raise their prices and sell MORE. So higher prices DO increase revenue.',
      defense: {
        label: 'Exceptions and inelastic demand',
        description: 'Luxury/Veblen goods are an exception where high price signals status; also some goods have inelastic demand where revenue rises. That does not make the claim "always" true. It depends on elasticity.',
        patterns: [/veblen/, /luxury.{0,30}(exception|special|different|status)/, /prestige|status (good|symbol)|exclusiv/, /inelastic/, /(not|isn'?t) always/, /exception/, /(brand|marketing|image) (changes?|shifts?)/, /shift/, /depends/],
      },
      followUp: 'Does one special category of goods make the word "always" true? What makes luxury goods different?',
    },
    evidenceExamples: ['If a café raises coffee from $3 to $4 and sales fall from 100 to 60 cups, revenue drops from $300 to $240.'],
    acceptableReasoning: 'Revenue = P × Q; higher price lowers quantity; if demand is elastic the drop in Q outweighs the rise in P and revenue falls; if inelastic, revenue may rise.',
    hints: [
      'Revenue has two ingredients. The claim only talks about one.',
      'Revenue = price × quantity. What happens to quantity when price rises?',
      'Economists have a word for how sensitive buyers are to price changes.',
      'Price elasticity of demand: if buyers are very price-sensitive (elastic), quantity falls by a larger percentage than price rises, so revenue drops.',
    ],
    solution: {
      summary: 'Whether a price increase raises revenue depends on price elasticity of demand.',
      explanation: 'Revenue = price × quantity. When demand is elastic, a price rise causes a proportionally larger fall in quantity, so revenue falls. Only with inelastic demand does revenue rise. Luxury/Veblen goods are rare exceptions.',
    },
    keywords: ['price', 'revenue', 'demand', 'company', 'increase', 'sell', 'customers', 'money'],
  },
  {
    id: 'eco-opportunity-cost',
    subject: 'economics',
    topic: 'Opportunity cost',
    difficulty: 2,
    objective: 'The student can explain that the true cost of a choice includes the value of the best alternative given up.',
    claim: 'A free concert costs you nothing, so going is always the rational choice.',
    scaffold: 'What do you give up when you spend an evening at the concert?',
    concepts: [
      {
        id: 'opportunity_cost',
        label: 'Opportunity cost',
        description: 'The cost of a choice includes the value of the next-best alternative you give up.',
        patterns: [/opportunity cost/, /give up|giving up|gave up/, /forgo|forego/, /(could|would) (have|be|instead)/, /alternative/, /trade.?off/, /instead/, /next.?best/],
        followUp: 'If you go to the concert, what are you NOT doing with that evening?',
      },
      {
        id: 'nonmoney_costs',
        label: 'Costs are not only money',
        description: 'Time, effort, travel, and missed earnings or study are real costs even when the ticket is free.',
        patterns: [/\btime\b/, /hours?/, /(work|shift|job|wage|earn|pay)/, /stud(y|ying)|exam|homework/, /travel|transport|bus|gas|parking|food|drinks/],
        followUp: 'Besides money, what resources does going to the concert use up?',
      },
    ],
    clue: 'opportunity_cost',
    misconceptions: [
      {
        id: 'cost_is_money',
        label: 'Thinking cost means only money',
        patterns: [/cost (is|means) (only )?money/, /free means (no|zero) cost/, /no money (so|means) no cost/],
        correction: 'In economics, cost includes what you sacrifice, not just what you pay.',
        socratic: 'If you skipped a paid shift to attend, would the concert still be "free" for you?',
      },
    ],
    counter: {
      text: 'But if I had absolutely nothing else to do that night, then it truly costs nothing.',
      defense: {
        label: 'There is always a next-best alternative',
        description: 'Even "doing nothing" (resting, sleeping, relaxing) has value, and there may be travel or food costs. The opportunity cost may be small, but the rational choice still compares values.',
        patterns: [/rest|sleep|relax|free time|leisure/, /next.?best/, /always (an|some) (alternative|option|cost)/, /small(er)? (cost|opportunity)|low (cost|opportunity)/, /travel|transport|food|parking|energy|tired/, /still (a|some) cost/, /(worth|value)/],
      },
      followUp: 'Is "nothing" really worth nothing? Could the cost just be small rather than zero?',
    },
    evidenceExamples: ['A student who skips a $60 shift to go has an opportunity cost of at least $60 plus travel.'],
    acceptableReasoning: 'Cost includes the value of the best alternative forgone (time, wages, study); "free" tickets are not free choices; rationality means comparing benefit to opportunity cost.',
    hints: [
      'Money is not the only thing you spend.',
      'What else could you do with those four hours?',
      'Economists count the value of the best thing you give up.',
      'Opportunity cost: the value of the next-best alternative (work, study, rest). A free ticket can still be a costly choice.',
    ],
    solution: {
      summary: 'Every choice has an opportunity cost: the value of the best alternative given up.',
      explanation: 'A free ticket still costs time, travel, and whatever else you could have done (work, study, rest). Going is rational only if its benefit exceeds that opportunity cost, so it is not "always" rational.',
    },
    keywords: ['free', 'concert', 'cost', 'rational', 'choice', 'nothing', 'money'],
  },
  {
    id: 'eco-money-printing',
    subject: 'economics',
    topic: 'Inflation',
    difficulty: 3,
    objective: 'The student can explain why creating money without more goods and services tends to cause inflation rather than real wealth.',
    claim: 'If the government prints more money and gives it to everyone, everyone becomes richer.',
    scaffold: 'Real wealth is about what you can buy. Does printing money create more things to buy?',
    concepts: [
      {
        id: 'inflation',
        label: 'Prices rise (inflation)',
        description: 'More money chasing the same goods pushes prices up, so each unit of money buys less.',
        patterns: [/inflation/, /prices? (would |will )?(rise|go up|increase|climb)/, /(value|worth) of (the )?money (falls|drops|decreases|goes down)/, /purchasing power/, /(buys?|worth) less/],
        followUp: 'If everyone suddenly has twice as much money, what do sellers do with their prices?',
      },
      {
        id: 'real_output',
        label: 'Wealth depends on real goods and services',
        description: 'Printing money does not create more goods or services. Real wealth depends on production.',
        patterns: [/goods|services|products|stuff/, /production|produce|output/, /real (wealth|value|terms)/, /nothing new (is )?(made|produced)/, /same amount of/],
        followUp: 'Does printing money create more bread, houses, or phones?',
      },
    ],
    clue: 'real_output',
    misconceptions: [
      {
        id: 'money_is_wealth',
        label: 'Equating money with wealth',
        patterns: [/more money (means|=|is) (more )?(wealth|rich)/, /money is wealth/],
        correction: 'Money is a claim on goods and services. If goods do not increase, more money just means higher prices.',
        socratic: 'If every price tag doubled on the same day your money doubled, would you be richer?',
      },
    ],
    counter: {
      text: 'But during recessions, central banks create money and it helps the economy recover. So more money DOES make people richer.',
      defense: {
        label: 'It depends on unused capacity',
        description: 'When there are idle workers and factories, extra money can boost spending and output without much inflation. That is different from an economy at full capacity. The effect depends on circumstances and is short-run.',
        patterns: [/recession/, /unused|idle|spare capacity|slack/, /unemploy/, /short.?(term|run)/, /long.?(term|run)/, /depends|circumstances|context/, /(boost|stimulat|increase)s? (spending|demand|output|production)/, /full capacity/],
      },
      followUp: 'What is different about an economy in recession, with idle workers and factories?',
    },
    evidenceExamples: ['Zimbabwe (2000s) and Weimar Germany (1923) printed money rapidly and saw hyperinflation.'],
    acceptableReasoning: 'Wealth = goods/services; printing money without more output raises prices; purchasing power unchanged or worse; in recessions with slack, money can help output short-term.',
    hints: [
      'Think about what money is actually for.',
      'If everyone has more money but there are no more goods, what happens to prices?',
      'Economists call a general rise in prices by a specific name.',
      'Inflation: more money chasing the same goods raises prices, so real wealth (what money buys) does not increase unless production does.',
    ],
    solution: {
      summary: 'Printing money without more production causes inflation instead of real wealth.',
      explanation: 'Real wealth is goods and services. More money chasing the same output pushes prices up, so purchasing power does not rise. In a recession with idle resources, extra money can temporarily lift output, which is why it "helps" there.',
    },
    keywords: ['money', 'print', 'government', 'richer', 'wealth', 'everyone', 'economy'],
  },
  {
    id: 'eco-comparative-advantage',
    subject: 'economics',
    topic: 'Comparative advantage',
    difficulty: 4,
    objective: 'The student can explain why trade benefits both countries through comparative advantage, even when one is better at everything.',
    claim: 'If Country A can produce both cars and wheat more efficiently than Country B, A gains nothing by trading with B.',
    scaffold: 'What does A give up each time it makes a car instead of wheat?',
    concepts: [
      {
        id: 'comparative_advantage',
        label: 'Comparative advantage',
        description: 'What matters is relative (opportunity) cost, not absolute efficiency. B can have a lower opportunity cost in one good.',
        patterns: [/comparative advantage/, /relative(ly)? (efficien|cost|better|cheaper)/, /opportunity cost/, /absolute advantage/, /(gives? up|sacrific)/],
        followUp: 'Even if A is better at both, is A equally better at both? What does each country give up to produce each good?',
      },
      {
        id: 'specialization',
        label: 'Specialization raises total output',
        description: 'If each country specializes in its lower-opportunity-cost good and trades, total output rises and both can gain.',
        patterns: [/speciali[sz]/, /focus(es)? on/, /concentrat/, /(total|combined|overall) (output|production)/, /(both|each) (countries )?(gain|benefit|better off)/, /more (in total|overall)/],
        followUp: 'What happens to total production if each country focuses on what it gives up least to make?',
      },
    ],
    clue: 'comparative_advantage',
    misconceptions: [
      {
        id: 'absolute_only',
        label: 'Thinking only absolute advantage matters',
        patterns: [/better at (both|everything) (so|means)/, /(only|just) (the )?(stronger|better|richer) (country )?(gains|benefits)/, /zero.?sum/],
        correction: 'Absolute advantage is not what drives gains from trade; relative (opportunity) cost is.',
        socratic: 'A surgeon may type faster than her assistant. Should she still do all her own typing? What does she give up?',
      },
    ],
    counter: {
      text: 'Even if the total grows, trade only really helps the stronger country. The weaker one just gets exploited.',
      defense: {
        label: 'Both gain, though gains may be uneven',
        description: 'With comparative advantage, both countries can consume beyond what they could produce alone. The split of gains depends on the terms of trade and may be unequal, but trade is not zero-sum.',
        patterns: [/both (countries )?(gain|benefit|better)/, /terms of trade/, /(split|share|distribution) (of )?(the )?gains/, /(uneven|unequal)/, /not zero.?sum|positive.?sum/, /(more|beyond) than (they )?(could )?(produce|make) alone/, /mutual/],
      },
      followUp: 'Can B end up consuming more than it could produce alone? Who decides how the gains are split?',
    },
    evidenceExamples: ['If A gives up 2 wheat per car but B gives up 4, A should specialize in cars and B in wheat.'],
    acceptableReasoning: 'Gains come from comparative (relative) advantage; opportunity costs differ; specialization + trade raises total output; both can gain.',
    hints: [
      'Being better at something is not the same as being *relatively* better at it.',
      'Compare what each country gives up to make one car.',
      'Economists distinguish absolute advantage from another kind.',
      'Comparative advantage: if each country specializes in the good with the lower opportunity cost and trades, total output rises and both can gain.',
    ],
    solution: {
      summary: 'Trade gains come from comparative advantage (lower opportunity cost), not absolute advantage.',
      explanation: 'Even if A is better at both, its opportunity cost differs between cars and wheat. If each specializes where its opportunity cost is lower and they trade, total output rises and both can consume more, though the split of gains may be uneven.',
    },
    keywords: ['country', 'trade', 'cars', 'wheat', 'efficient', 'gain', 'produce'],
  },
];
