// Computer Science challenges. Code is Python because it is the most
// common first language for students.

export default [
  {
    id: 'cs-types-input',
    subject: 'cs',
    topic: 'Data types',
    difficulty: 1,
    objective: 'The student can explain why combining a string and a number causes a type error.',
    claim: 'This program crashes because the variable `age` is declared incorrectly. Prove me wrong.',
    code: 'age = input("How old are you? ")\nprint(age + 1)',
    scaffold: 'Think about what kind of value input() gives back.',
    concepts: [
      {
        id: 'string_value',
        label: 'input() returns text (a string)',
        description: 'input() always returns a string, even if the user types digits.',
        patterns: [/\bstr(ing)?s?\b/, /\btext\b/, /returns? (a )?(str|text|string)/, /not an? (int|integer|number)/],
        followUp: 'What kind of value does input() actually hand back to the program?',
      },
      {
        id: 'type_mismatch',
        label: 'You cannot add a string and a number',
        description: 'Python raises a TypeError when you try to add a string and an integer, because the types are incompatible.',
        patterns: [/type ?error/, /(can'?t|cannot|can not|unable to) (add|combine|concatenate|mix)/, /(different|incompatible|mismatch(ed)?) types?/, /type mismatch/, /(string|str|text).{0,30}(\+|plus|add).{0,30}(int|number|integer|1)/, /(int|number|integer).{0,30}(\+|plus|add).{0,30}(string|str|text)/],
        followUp: 'So what exactly goes wrong on the line `age + 1`?',
      },
      {
        id: 'convert_fix',
        label: 'Convert with int()',
        description: 'Converting with int(age) fixes the problem.',
        patterns: [/int\s*\(/, /\bconvert/, /\bcast/, /\bparse/],
        required: false,
        followUp: 'How would you fix it?',
      },
    ],
    clue: 'string_value',
    misconceptions: [
      {
        id: 'needs_declaration',
        label: 'Thinking Python variables need a type declaration',
        patterns: [/(need|needs|must|should) (to )?(be )?(declared?|use|have) (with )?(a )?(type|var|let|int)/, /declar(e|ed|ation).{0,20}(wrong|incorrect|missing)/, /missing (var|let|int)/],
        correction: 'Python variables do not need declarations. `age = ...` is perfectly valid. The problem is the *value* stored in it.',
        socratic: 'Does Python ever require you to declare a variable\'s type before using it? If `age = ...` is fine, where else could the problem be?',
      },
    ],
    counter: {
      text: 'But `age + 1` works fine in JavaScript! So the language must be broken, not the code.',
      defense: {
        label: 'Languages handle types differently',
        description: 'JavaScript silently converts (coerces) the number to text and produces "201" rather than 21. Python is strongly typed and refuses, which surfaces the bug instead of hiding it.',
        patterns: [/coerc/, /concatenat/, /"?\b\d+1\b"?/, /strong(ly)? typed/, /different (languages|rules)/, /(javascript|js).{0,40}(string|text|convert|join)/, /(hid(e|es|ing)|silent)/, /(wrong|weird|unexpected) (result|answer|output)/],
      },
      followUp: 'What does JavaScript actually output for "20" + 1? Is that really "working"?',
    },
    evidenceExamples: ['Typing 20 gives the string "20"; "20" + 1 raises TypeError: can only concatenate str (not "int") to str.'],
    acceptableReasoning: 'input() returns a string; adding an int to a string is a TypeError; the variable name/declaration is fine; fix with int().',
    hints: [
      'The variable name is fine. Look at the *value* stored in it.',
      'What does input() return when the user types 20?',
      'input() gives back text. What happens when you add text and a number?',
      'input() always returns a string. "20" + 1 mixes a string and an int, so Python raises a TypeError. Converting with int() fixes it.',
    ],
    solution: {
      summary: 'input() returns a string, and Python will not add a string and an integer.',
      explanation: 'The variable is fine. Python does not need declarations. input() returns the string "20", and "20" + 1 raises TypeError because the types are incompatible. Fix: age = int(input(...)).',
    },
    keywords: ['input', 'age', 'print', 'crash', 'error', 'variable', 'number', 'python', 'declare'],
  },
  {
    id: 'cs-loop-index',
    subject: 'cs',
    topic: 'Loops & arrays',
    difficulty: 2,
    objective: 'The student can explain how zero-based indexing causes an off-by-one error in a loop.',
    claim: 'The average printed here is wrong because Python cannot divide integers correctly. Prove me wrong.',
    code: 'scores = [70, 85, 90]\ntotal = 0\nfor i in range(1, len(scores)):\n    total = total + scores[i]\nprint(total / len(scores))',
    scaffold: 'Trace the loop by hand: which values of i does it visit?',
    concepts: [
      {
        id: 'zero_index',
        label: 'Lists start at index 0',
        description: 'Python list indexes start at 0, so scores[0] (70) is the first element.',
        patterns: [/(start|begin)s? (at|from|with) (0|zero)/, /zero.?based|0.?based/, /index(es)? (0|zero)/, /\[0\]/, /first (element|item|score|value|number)/],
        followUp: 'At what index does a Python list start?',
      },
      {
        id: 'skipped_element',
        label: 'The loop skips the first element',
        description: 'range(1, len(scores)) starts at 1, so 70 is never added. total is 175 instead of 245.',
        patterns: [/skip/, /miss(es|ed|ing)?/, /(never|not) (added|included|counted)/, /(ignore|leave)s? (out )?(the )?(first|70)/, /range\s*\(\s*1/, /off.?by.?one/, /\b175\b/, /only (adds|sums|counts) (two|2)/],
        followUp: 'Which of the three scores actually get added to total?',
      },
      {
        id: 'loop_fix',
        label: 'Fix the loop range',
        description: 'Use range(len(scores)), iterate directly over scores, or use sum().',
        patterns: [/range\s*\(\s*(0\s*,\s*)?len/, /for \w+ in scores/, /sum\s*\(/],
        required: false,
        followUp: 'How would you fix the loop?',
      },
    ],
    clue: 'skipped_element',
    misconceptions: [
      {
        id: 'division_broken',
        label: 'Thinking integer division is the problem',
        patterns: [/(integer|int) division/, /(can'?t|cannot) divide/, /division (is )?(wrong|broken|the problem)/, /round(s|ing)? (down|off)/],
        correction: 'In Python 3, `/` always produces an accurate decimal: 245 / 3 = 81.67. The division is fine. Check what is being divided.',
        socratic: 'If you computed 245 / 3 in Python, would you get the right answer? So is the division really the suspect, or the number going into it?',
      },
    ],
    counter: {
      text: 'The division uses len(scores), which is 3, but only two numbers were added. So maybe len() is the real bug!',
      defense: {
        label: 'len() is correct; the loop is the bug',
        description: 'There ARE three scores, so len() = 3 is right. The average should divide by 3; the loop is what failed to add all three.',
        patterns: [/len.{0,25}(correct|right|fine|accurate|3|three)/, /(there are|has) (3|three)/, /loop.{0,25}(bug|wrong|problem|skip|fault)/, /(not|isn'?t) (the )?len/, /should divide by (3|three)/],
      },
      followUp: 'How many scores are actually in the list? What should we divide by?',
    },
    evidenceExamples: ['Tracing: i=1 adds 85, i=2 adds 90, total=175; 175/3 = 58.33 instead of 245/3 = 81.67.'],
    acceptableReasoning: 'Indexes start at 0; range(1, ...) skips scores[0]; total is too small; division and len() are fine.',
    hints: [
      'The division is innocent. Look at what goes into it.',
      'Write down every value of i the loop takes.',
      'range(1, 3) produces 1 and 2. What index holds 70?',
      'Lists are zero-indexed: 70 lives at scores[0]. range(1, len(scores)) starts at 1 and skips it, so total is 175 instead of 245.',
    ],
    solution: {
      summary: 'Lists are zero-indexed; starting the loop at 1 skips the first element (an off-by-one error).',
      explanation: 'range(1, len(scores)) visits i = 1 and 2, so only 85 and 90 are added (175). Division by len(scores) = 3 is correct. Fix: range(len(scores)), or simply sum(scores) / len(scores).',
    },
    keywords: ['loop', 'range', 'index', 'average', 'divide', 'len', 'scores', 'total'],
  },
  {
    id: 'cs-scope',
    subject: 'cs',
    topic: 'Functions & scope',
    difficulty: 2,
    objective: 'The student can explain why a variable created inside a function is not accessible outside it.',
    claim: 'This program crashes because add_bonus returns the wrong value. Prove me wrong.',
    code: 'def add_bonus(points):\n    bonus = 10\n    return points + bonus\n\ntotal = add_bonus(5)\nprint(bonus)',
    scaffold: 'Check which line actually crashes. Does the function itself work?',
    concepts: [
      {
        id: 'local_scope',
        label: 'bonus is a local variable',
        description: 'bonus is created inside the function, so it only exists in the function\'s local scope.',
        patterns: [/\blocal/, /\bscope/, /(inside|within|in) the function/, /only exists? (in|inside)/, /defined (inside|in)/],
        followUp: 'Where is `bonus` created, and where are we trying to use it?',
      },
      {
        id: 'name_error',
        label: 'Using it outside raises NameError',
        description: 'print(bonus) runs outside the function where bonus does not exist, raising NameError.',
        patterns: [/name ?error/, /not defined/, /undefined/, /(doesn'?t|does not|no longer) exist/, /(outside|after) (of )?the function/, /print\s*\(\s*bonus/, /last line/],
        followUp: 'Which line actually crashes, and what error would Python report?',
      },
      {
        id: 'return_ok',
        label: 'The function returns 15 correctly',
        description: 'add_bonus(5) correctly returns 15.',
        patterns: [/\b15\b/, /returns? (the )?(right|correct)/, /function (works|is fine)/],
        required: false,
        followUp: 'What does add_bonus(5) return?',
      },
    ],
    clue: 'name_error',
    misconceptions: [
      {
        id: 'global_by_default',
        label: 'Thinking variables inside functions are global',
        patterns: [/(variables?|bonus) (is|are) (global|shared|available everywhere)/, /return(s)? (the )?wrong/],
        correction: 'add_bonus(5) returns 15, which is correct. Variables created inside a function are local to it; they vanish when the function ends.',
        socratic: 'What would add_bonus(5) return? And once the function finishes, does its variable `bonus` still exist?',
      },
    ],
    counter: {
      text: 'If I write `bonus = 0` at the top of the file, the function will change it to 10. So variables are shared everywhere after all.',
      defense: {
        label: 'Assignment inside creates a new local',
        description: 'Assigning bonus = 10 inside the function creates a separate local variable that shadows the outer one; the outer bonus stays 0 unless you use the global keyword.',
        patterns: [/(new|separate|different|own) (local )?(variable|copy|bonus|namespace)/, /global keyword/, /shadow/, /stays? (0|zero)/, /(still|remain)s? (0|zero)/, /unless.{0,20}global/],
      },
      followUp: 'After calling the function, what would print(bonus) show at the top level: 0 or 10?',
    },
    evidenceExamples: ['Running it prints NameError: name \'bonus\' is not defined on the last line; total is 15.'],
    acceptableReasoning: 'The function works (returns 15); bonus is local to add_bonus; print(bonus) outside raises NameError.',
    hints: [
      'The function\'s math is fine. Which line would Python complain about?',
      'Where does the variable `bonus` live?',
      'Variables created inside a function have a limited lifetime and visibility.',
      '`bonus` is local to add_bonus. The last line tries to print it outside the function, so Python raises NameError.',
    ],
    solution: {
      summary: 'Variables created inside a function are local to it; using them outside raises NameError.',
      explanation: 'add_bonus(5) correctly returns 15. But bonus only exists inside the function\'s scope. print(bonus) at the top level raises NameError: name \'bonus\' is not defined. Print total instead.',
    },
    keywords: ['function', 'bonus', 'return', 'print', 'variable', 'crash', 'error'],
  },
  {
    id: 'cs-condition-order',
    subject: 'cs',
    topic: 'Conditions',
    difficulty: 3,
    objective: 'The student can explain how the order of if/elif branches determines which branch runs.',
    claim: 'This function never returns "distinction" because 90 is too big a number for an if-statement. Prove me wrong.',
    code: 'def grade_label(grade):\n    if grade >= 50:\n        return "pass"\n    elif grade >= 90:\n        return "distinction"\n    else:\n        return "fail"',
    scaffold: 'Try grade_label(95) by hand, line by line.',
    concepts: [
      {
        id: 'first_match',
        label: 'The first true condition wins',
        description: 'if/elif conditions are checked top to bottom and only the first true branch runs.',
        patterns: [/(checked|evaluated|runs?) (first|in order|top)/, /top to bottom/, /first (true|matching|condition)/, /\border\b/, /(already|also) (true|matches|matched|catches)/, />= ?50.{0,40}(true|first|catch)/, /(95|90|any).{0,30}(is|are) (also )?(>=|greater|above|over) ?50/],
        followUp: 'For a grade of 95, which condition is checked first, and is it true?',
      },
      {
        id: 'unreachable',
        label: 'The distinction branch is unreachable',
        description: 'Any grade >= 90 is also >= 50, so the elif can never run. It is dead code.',
        patterns: [/never (reached|runs?|executed|checked)/, /unreachable/, /dead code/, /(can|could) never/, /only one branch/, /(skips?|ignores?) the elif/, /stops? (at|after)/],
        followUp: 'Can the elif branch ever run? Why not?',
      },
      {
        id: 'reorder_fix',
        label: 'Check the bigger threshold first',
        description: 'Put the >= 90 check before the >= 50 check.',
        patterns: [/(reorder|swap|switch|flip|reverse)/, /(put|move|check).{0,20}90.{0,20}(first|before|above|top)/],
        required: false,
        followUp: 'How would you fix it?',
      },
    ],
    clue: 'first_match',
    misconceptions: [
      {
        id: 'number_too_big',
        label: 'Thinking numbers can be "too big" for a condition',
        patterns: [/too (big|large|high)/, /overflow/, /(max|maximum|limit)/],
        correction: 'Conditions can compare any numbers; 90 is tiny for a computer. The problem is *when* the check happens.',
        socratic: 'Would `if 95 >= 90:` on its own be True? If so, the number is not the problem. What happens before that line is reached?',
      },
    ],
    counter: {
      text: 'Easy fix: change `elif` to `if`. Then both conditions get checked, and it works.',
      defense: {
        label: 'return exits immediately',
        description: 'Changing elif to if does not help: `return "pass"` exits the function as soon as the first condition is true, so the second check is still never reached. Reordering is the real fix.',
        patterns: [/return.{0,30}(exits?|leaves?|ends?|stops?|immediately|first)/, /still (return|gives|outputs?)s? .{0,5}pass/, /(never|still not) (reach|get)/, /reorder|swap|put.{0,15}90.{0,15}first/],
      },
      followUp: 'What does `return` do to the rest of the function once it runs?',
    },
    evidenceExamples: ['grade_label(95): 95 >= 50 is True, so it returns "pass" before the elif is ever checked.'],
    acceptableReasoning: 'if/elif runs the first true branch; >= 50 catches all grades >= 90 first, making distinction unreachable; reorder the checks.',
    hints: [
      'The number 90 is not the problem. The order of the lines might be.',
      'Trace grade_label(95). Which line is checked first?',
      'Is 95 >= 50? What happens right after that is True?',
      'Conditions are checked top to bottom and the first true one wins. Every grade >= 90 is also >= 50, so "pass" is returned first and "distinction" is unreachable.',
    ],
    solution: {
      summary: 'if/elif runs only the first true branch, so conditions must go from most to least specific.',
      explanation: 'Every grade >= 90 is also >= 50, so the first branch returns "pass" and the elif is unreachable. Checking >= 90 first fixes it. Changing elif to if does not help because return exits immediately.',
    },
    keywords: ['if', 'elif', 'grade', 'distinction', 'pass', 'condition', 'return', '90', '50'],
  },
  {
    id: 'cs-search-tradeoff',
    subject: 'cs',
    topic: 'Algorithms',
    difficulty: 4,
    objective: 'The student can explain the requirements and costs that decide when binary search beats linear search.',
    claim: 'Binary search is always faster than linear search, so you should always use binary search.',
    scaffold: 'What does binary search need to be true about the data before it can work?',
    concepts: [
      {
        id: 'needs_sorted',
        label: 'Binary search needs sorted data',
        description: 'Binary search only works if the data is already sorted.',
        patterns: [/\bsort/, /\border(ed)?\b/],
        followUp: 'What must be true about the list before binary search can work at all?',
      },
      {
        id: 'sorting_cost',
        label: 'Sorting has a cost',
        description: 'Sorting unsorted data costs O(n log n), more than a single O(n) linear search, and small lists gain little.',
        patterns: [/n ?log ?n/, /sort(ing)? (costs?|takes|is (slow|expensive))/, /(cost|time|expensive).{0,20}(to )?sort/, /small (list|array|data)/, /(few|handful of) (items|elements)/, /(once|one time|single search|one search)/, /overhead/],
        followUp: 'If the data is not sorted yet, what does it cost to get it into a state where binary search works?',
      },
      {
        id: 'complexity',
        label: 'O(n) vs O(log n)',
        description: 'Linear search is O(n); binary search is O(log n) because it halves the search space each step.',
        patterns: [/o\s*\(\s*n\s*\)/, /o\s*\(\s*log/, /logarithm/, /halv|half|divide/, /linear time/],
        required: false,
        followUp: 'How does the number of steps grow for each search?',
      },
    ],
    clue: 'needs_sorted',
    misconceptions: [
      {
        id: 'works_unsorted',
        label: 'Thinking binary search works on unsorted data',
        patterns: [/binary search (works|can work) on (any|unsorted)/, /(any|unsorted) (list|data|array).{0,20}binary/],
        correction: 'Binary search decides which half to discard by comparing to the middle element. That only makes sense if the data is sorted.',
        socratic: 'If binary search looks at the middle item and throws away half the list, how does it know which half is safe to discard?',
      },
    ],
    counter: {
      text: 'Fine, but sorting is a one-time cost. After that, binary search wins every time. So it still always wins.',
      defense: {
        label: 'Only if you search many times and data stays stable',
        description: 'Sorting pays off only across many searches. If you search once, or the data changes often (requiring re-sorting or costly sorted inserts), linear search can be cheaper.',
        patterns: [/(many|multiple|repeated|lots of) (searches|times|lookups|queries)/, /only (once|one search|a few)/, /(chang|updat|insert|add)(es|ing|s)?.{0,25}(often|frequent|re-?sort|keep sorted|again)/, /amortiz/, /depends on how (many|often)/],
      },
      followUp: 'What if you only search once? Or new items are added all the time?',
    },
    evidenceExamples: ['For 1,000,000 unsorted items searched once: linear ~1,000,000 steps; sort + binary ~20,000,000 + 20.'],
    acceptableReasoning: 'Binary search requires sorted data; sorting costs O(n log n); worth it only for many searches on stable data.',
    hints: [
      'Binary search has a precondition. What is it?',
      'Binary search throws away half the data at each step. How does it know which half?',
      'The data must be sorted, and sorting is not free.',
      'Binary search needs sorted data. Sorting costs O(n log n), more than one O(n) linear search, so binary search only wins for repeated searches on stable data.',
    ],
    solution: {
      summary: 'Binary search requires sorted data; whether it is faster depends on the cost of sorting versus how many searches you do.',
      explanation: 'Binary search is O(log n) but only on sorted data. Sorting costs O(n log n). For a single search, or data that changes often, linear search (O(n)) can be cheaper overall.',
    },
    keywords: ['binary', 'linear', 'search', 'faster', 'algorithm', 'list', 'data', 'speed'],
  },
  {
    id: 'cs-float-precision',
    subject: 'cs',
    topic: 'Floating-point numbers',
    difficulty: 5,
    objective: 'The student can explain why decimal fractions cannot be stored exactly in binary floating point and how to compare them safely.',
    claim: 'This prints "not equal" because Python has a bug in its addition.',
    code: 'total = 0.1 + 0.2\nif total == 0.3:\n    print("equal")\nelse:\n    print("not equal")',
    scaffold: 'How does a computer store 0.1 in binary?',
    concepts: [
      {
        id: 'binary_representation',
        label: 'Some decimals cannot be stored exactly in binary',
        description: '0.1 and 0.2 have infinite binary expansions, so they are stored as close approximations.',
        patterns: [/binary|base.?2/, /(can'?t|cannot|not) be (represented|stored) exactly/, /approximat/, /precision/, /ieee/, /floating.?point/, /0\.30000000000000004/, /rounding error/],
        followUp: 'How is 0.1 actually stored inside the computer?',
      },
      {
        id: 'safe_comparison',
        label: 'Compare with a tolerance',
        description: 'Compare floats with a tolerance, e.g. math.isclose or abs(a - b) < 1e-9, or use Decimal for exact decimal arithmetic.',
        patterns: [/tolerance/, /epsilon/, /isclose/, /abs\s*\(/, /\bround/, /decimal/, /fraction/, /close enough/],
        followUp: 'How should a programmer compare two floating-point numbers instead of ==?',
      },
    ],
    clue: 'binary_representation',
    misconceptions: [
      {
        id: 'python_bug',
        label: 'Thinking this is a Python bug',
        patterns: [/(python|it) (has|is) (a )?(bug|broken)/, /python bug/],
        correction: 'This is not a Python bug. It comes from how nearly all hardware stores decimals in binary (IEEE 754).',
        socratic: 'If you tried this in JavaScript, Java, or C, what would you expect? What would that tell you about where the problem comes from?',
      },
    ],
    counter: {
      text: 'If this happens, Python should just fix it. A language that cannot add 0.1 + 0.2 is broken.',
      defense: {
        label: 'It is a standard trade-off, not a bug',
        description: 'Nearly every language uses the IEEE 754 standard in hardware for speed. It is a deliberate trade-off between speed and exactness; exact types like Decimal exist when precision matters (e.g. money).',
        patterns: [/(all|most|every|other) (languages|programming)/, /javascript|java\b|c\+\+|\bc\b/, /hardware/, /standard/, /ieee/, /trade.?off/, /speed|fast/, /decimal (type|module)/, /money|currency|finance/],
      },
      followUp: 'Would another language give a different answer? Why might designers accept this?',
    },
    evidenceExamples: ['print(0.1 + 0.2) shows 0.30000000000000004 in Python, JavaScript, Java, and C.'],
    acceptableReasoning: 'Binary floating point approximates 0.1 and 0.2; the sum differs slightly from 0.3; use tolerances or Decimal; universal, not a Python bug.',
    hints: [
      'Try printing 0.1 + 0.2 in your head. Would it really show exactly 0.3?',
      'Computers store numbers in base 2. Is 0.1 a "nice" number in base 2?',
      '1/3 cannot be written exactly in decimal. 0.1 has the same problem in binary.',
      '0.1 and 0.2 are stored as binary approximations, so their sum is 0.30000000000000004. Compare floats with a tolerance (math.isclose) instead of ==.',
    ],
    solution: {
      summary: 'Floating-point numbers are binary approximations; compare them with a tolerance, not ==.',
      explanation: '0.1 and 0.2 have infinite binary expansions, so they are stored approximately; their sum is 0.30000000000000004. This IEEE 754 behavior exists in almost every language. Use math.isclose or Decimal.',
    },
    keywords: ['0.1', '0.2', '0.3', 'equal', 'float', 'add', 'python', 'bug', 'number'],
  },
];
