// Psychology challenges are scenario-based: the player compares hypotheses
// instead of naming a term.

export default [
  {
    id: 'psy-audience',
    subject: 'psychology',
    topic: 'Social facilitation & inhibition',
    difficulty: 2,
    objective: 'The student can explain how the presence of an audience affects performance depending on task difficulty, and compare it to alternative explanations.',
    claim: 'A student solves hard puzzles well alone but performs much worse when a crowd is watching. They must simply be bad at puzzles.',
    scaffold: 'What changed between the two situations?',
    concepts: [
      {
        id: 'audience_effect',
        label: 'The audience changes performance',
        description: 'The presence of others (being watched and evaluated) changes performance: social facilitation/inhibition.',
        patterns: [/social (facilitation|inhibition)/, /audience/, /being (watched|observed|judged)/, /presence of (others|people)/, /(crowd|people) (watching|looking)/, /watched/],
        followUp: 'They solve the same puzzles well alone. So what actually changed?',
      },
      {
        id: 'arousal',
        label: 'Arousal / evaluation anxiety',
        description: 'Being watched raises arousal and evaluation anxiety, which disrupts performance on difficult or unfamiliar tasks.',
        patterns: [/arous/, /anxi|nervous|stress|pressure|panic|choke|choking/, /self.?conscious|embarrass/, /(fear|worry) (of|about) (being )?(judg|evaluat|fail)/, /evaluat/],
        followUp: 'What happens inside a person when they feel they are being judged?',
      },
      {
        id: 'task_difficulty',
        label: 'The effect depends on task difficulty',
        description: 'Audiences tend to improve performance on easy/well-practiced tasks and impair it on hard/new tasks.',
        patterns: [/(easy|simple|well.?(learned|practiced)|familiar).{0,40}(better|improve)/, /(hard|difficult|complex|new|unfamiliar).{0,40}(worse|impair|hurt)/, /depends on (the )?(task|difficulty)/],
        required: false,
        followUp: 'Would an audience have the same effect on a very easy task?',
      },
    ],
    clue: 'audience_effect',
    misconceptions: [
      {
        id: 'fixed_ability',
        label: 'Assuming performance reflects fixed ability',
        patterns: [/(just|simply) (bad|not good|not smart)/, /(lack|low) (of )?(ability|intelligence)/],
        correction: 'The same person performs well alone, so a fixed lack of ability cannot explain the drop. The situation changed.',
        socratic: 'If they are "bad at puzzles," why do they do well when alone?',
      },
    ],
    counter: {
      text: 'Maybe they were just tired on the day of the crowd. How would you tell the audience explanation apart from tiredness?',
      defense: {
        label: 'Test competing hypotheses',
        description: 'Compare the same person alone vs watched on the same day, repeat several times, and randomize the order; if performance only drops when watched, the audience explanation is supported.',
        patterns: [/(alone|without (an )?(audience|crowd)).{0,50}(compare|vs|versus|then|and)/, /compare|comparison/, /control/, /experiment|test (them|it|both)/, /same (day|person|time)/, /both conditions|each condition/, /random|repeat|several times|many times/, /measure/],
      },
      followUp: 'What experiment could separate "tired" from "being watched"?',
    },
    evidenceExamples: ['Zajonc (1965) and later studies: audiences improved simple task performance but impaired complex tasks.'],
    acceptableReasoning: 'Same person, different situation, so audience effect; arousal/evaluation anxiety impairs hard tasks; compare conditions to rule out tiredness.',
    hints: [
      'Their ability did not change between the two situations. What did?',
      'Think about how it feels to be watched while doing something hard.',
      'Psychologists study how the mere presence of others affects performance.',
      'Social inhibition: being watched raises arousal and evaluation anxiety, which hurts performance on difficult tasks (while often helping on easy ones).',
    ],
    solution: {
      summary: 'Audiences raise arousal: they help on easy tasks and hurt on hard ones (social facilitation/inhibition).',
      explanation: 'Performing well alone rules out a lack of ability. Being watched raises arousal and evaluation anxiety, which impairs hard or unfamiliar tasks. To rule out tiredness, compare the same person alone vs watched under otherwise identical conditions.',
    },
    keywords: ['crowd', 'watching', 'puzzles', 'alone', 'worse', 'perform', 'bad', 'student'],
  },
  {
    id: 'psy-horoscope',
    subject: 'psychology',
    topic: 'Cognitive biases',
    difficulty: 3,
    objective: 'The student can explain how confirmation bias and vague statements make horoscopes seem accurate.',
    claim: 'I read my horoscope every day and it\'s always accurate, so astrology works.',
    scaffold: 'Do you remember every prediction, or only the ones that fit?',
    concepts: [
      {
        id: 'confirmation_bias',
        label: 'Confirmation bias',
        description: 'People notice and remember hits and forget misses, so the horoscope seems more accurate than it is.',
        patterns: [/confirmation bias/, /remember (the |only )?(hits|ones that|times it)/, /(forget|ignore|overlook)s? (the )?(misses|wrong|times|ones)/, /notic(e|ing) (only|what)/, /selective/, /cherry.?pick/],
        followUp: 'Do you keep a record of the days it was wrong? Which days stick in your memory?',
      },
      {
        id: 'vague_statements',
        label: 'Vague statements fit anyone (Barnum effect)',
        description: 'Horoscopes use general statements that could apply to almost anyone, so they feel personal.',
        patterns: [/vague|general|generic|broad/, /barnum|forer/, /(apply|fit|relate)s? to (anyone|everyone|most people|anybody)/, /could (mean|fit) anything/],
        followUp: 'Could your horoscope\'s wording apply to your friends too?',
      },
    ],
    clue: 'vague_statements',
    misconceptions: [
      {
        id: 'feeling_is_evidence',
        label: 'Treating a feeling of accuracy as evidence',
        patterns: [/(feels|seems) (so )?accurate (so|therefore)/, /(it|they) (just )?know/],
        correction: 'Feeling that something is accurate is exactly what biases produce. Evidence needs a fair test.',
        socratic: 'How could you check whether it really predicts your day, instead of just feeling like it does?',
      },
    ],
    counter: {
      text: 'But millions of people say their horoscope is accurate for them. That many people can\'t all be wrong.',
      defense: {
        label: 'Popularity is not evidence; test it blind',
        description: 'The same biases operate in everyone, so many people can share an illusion. Controlled tests (e.g. people blindly matching horoscopes to themselves) perform at chance.',
        patterns: [/popular|bandwagon|ad populum/, /(everyone|many people|millions|they all).{0,30}(same )?bias/, /blind/, /control(led)?/, /(scientific )?test|experiment|study|studies/, /(many|lots of|millions of) people (can|have) (be |been )?wrong/, /match(ing)?/, /chance/],
      },
      followUp: 'If a bias affects everyone, does counting believers help? How could you test astrology fairly?',
    },
    evidenceExamples: ['Forer (1949) gave all students the same "personal" profile; they rated it 4.3/5 accurate. Carlson (1985) found astrologers matched charts at chance level.'],
    acceptableReasoning: 'Confirmation bias (remember hits, forget misses); vague Barnum statements fit anyone; popularity is not evidence; blind tests show chance-level accuracy.',
    hints: [
      'How do you know it is "always" accurate? Did you keep score?',
      'Read someone else\'s sign. Does it also fit you?',
      'People tend to notice evidence that supports what they already believe.',
      'Confirmation bias (we remember hits, forget misses) plus vague "Barnum" statements that fit almost anyone make horoscopes feel accurate.',
    ],
    solution: {
      summary: 'Confirmation bias and vague (Barnum) statements create an illusion of accuracy; only fair tests can evaluate a claim.',
      explanation: 'We notice and remember the hits and forget the misses (confirmation bias), and horoscopes use statements that fit almost anyone (Barnum effect). In controlled blind tests, people cannot pick their own horoscope above chance.',
    },
    keywords: ['horoscope', 'astrology', 'accurate', 'every day', 'works', 'read'],
  },
  {
    id: 'psy-breakfast',
    subject: 'psychology',
    topic: 'Correlation vs causation',
    difficulty: 4,
    objective: 'The student can explain why a correlation does not establish causation and identify plausible third variables.',
    claim: 'Students who eat breakfast get better grades, so eating breakfast makes you smarter.',
    scaffold: 'What else might be different about students who eat breakfast every day?',
    concepts: [
      {
        id: 'correlation',
        label: 'Correlation is not causation',
        description: 'Two things occurring together does not prove one causes the other.',
        patterns: [/correlat/, /causation|causal/, /(doesn'?t|does not|not) (necessarily )?(mean|prove|imply)/, /association|associated|linked/],
        followUp: 'Does the data show breakfast *causes* better grades, or just that they go together?',
      },
      {
        id: 'third_variable',
        label: 'Third variables',
        description: 'Other factors like family income, stable routines, sleep, or parental support could cause both breakfast-eating and better grades.',
        patterns: [/third variable|confound|other (factor|variable)/, /family|parent|home/, /income|wealth|money|rich|poor|socio/, /routine|organi[sz]ed|structure|habit|discipline/, /sleep/, /lifestyle|healthy/],
        followUp: 'What kind of home or routine tends to include breakfast every day? Could that affect grades too?',
      },
    ],
    clue: 'third_variable',
    misconceptions: [
      {
        id: 'correlation_proves',
        label: 'Treating a correlation as proof of cause',
        patterns: [/(proves|shows) (that )?breakfast (makes|causes)/, /data (proves|shows) (it )?causes/],
        correction: 'A correlation alone cannot tell us which way causation runs, or whether a third factor causes both.',
        socratic: 'Ice cream sales and drownings rise together. Does ice cream cause drowning? What connects them?',
      },
    ],
    counter: {
      text: 'OK, but breakfast gives your brain glucose. Isn\'t a causal link at least plausible?',
      defense: {
        label: 'Plausible, but needs an experiment',
        description: 'It may be partly causal, but plausibility is not evidence. A randomized experiment (assign breakfast vs no breakfast) is needed to separate the effect of breakfast from confounders.',
        patterns: [/plausib|possibl/, /partly|partially|both|some (of the )?effect|contribute/, /experiment/, /random(ly|ized|ised)? (assign|trial|control|group)|randomi[sz]/, /control(led)? (group|study|trial)/, /test (it|this)/, /need (more )?evidence/],
      },
      followUp: 'How could you find out how much of the effect is really breakfast?',
    },
    evidenceExamples: ['Randomized school breakfast trials show smaller or mixed effects compared with observational studies.'],
    acceptableReasoning: 'Correlation not causation; third variables (income, routine, sleep, parents); causal link plausible but requires randomized experiment.',
    hints: [
      'The data shows two things happen together. Is that the same as one causing the other?',
      'Think about what kind of home life includes breakfast every day.',
      'Researchers worry about hidden factors that influence both variables.',
      'Correlation is not causation: third variables like family income, routine or sleep could drive both breakfast habits and grades. Only an experiment can test causation.',
    ],
    solution: {
      summary: 'Correlation does not prove causation; third variables can explain both, and experiments are needed to test cause.',
      explanation: 'Breakfast-eaters may differ in family income, routines, sleep and parental support, and those could drive better grades. A causal effect is plausible, but only a randomized experiment can separate it from confounders.',
    },
    keywords: ['breakfast', 'grades', 'students', 'smarter', 'eat', 'better'],
  },
  {
    id: 'psy-bystander',
    subject: 'psychology',
    topic: 'Bystander effect',
    difficulty: 5,
    objective: 'The student can explain the bystander effect using situational mechanisms instead of personality, and describe its limits.',
    claim: 'A man collapses on a busy street and nobody helps for several minutes. This proves people today are just selfish.',
    scaffold: 'Would the same people help if they were alone with him?',
    concepts: [
      {
        id: 'diffusion',
        label: 'Diffusion of responsibility',
        description: 'In a crowd, each person feels less personally responsible and assumes someone else will act.',
        patterns: [/diffusion of responsibility/, /someone else (will|would|is going to|has)/, /bystander/, /responsibility (is )?(spread|shared|diffus|divided)/, /(nobody|no one) feels responsible/, /assume (others|another)/],
        followUp: 'When fifty people see the same emergency, how responsible does each one feel?',
      },
      {
        id: 'social_cues',
        label: 'Pluralistic ignorance / social cues',
        description: 'People look at others to interpret an ambiguous situation. When no one reacts, everyone concludes it is not an emergency.',
        patterns: [/pluralistic ignorance/, /look(ing|s)? (at|to) (others|each other|other people)/, /social (proof|cues?|influence)/, /(no one|nobody) else (is|was) (reacting|helping|doing)/, /ambigu|unclear|not (sure|obvious)/, /(maybe|thought) (he|it) (was )?(drunk|fine|sleeping)/],
        followUp: 'If you were unsure whether it was serious, where would you look for clues?',
      },
    ],
    clue: 'diffusion',
    misconceptions: [
      {
        id: 'personality_explanation',
        label: 'Explaining behavior by personality alone (fundamental attribution error)',
        patterns: [/(people|they) (are|were) (just )?(selfish|cold|mean|uncaring|bad)/, /nobody cares/, /society is (broken|selfish)/],
        correction: 'Studies show the same people help much more when alone. The situation, not selfishness, explains most of the delay.',
        socratic: 'If each of those people were alone with him, would they still walk past? What does that suggest about "selfishness"?',
      },
    ],
    counter: {
      text: 'But in some studies, people in groups DO help quickly. Doesn\'t that disprove the bystander effect?',
      defense: {
        label: 'The effect depends on conditions',
        description: 'The effect weakens when the emergency is clearly dangerous, when bystanders know each other, or when someone has relevant skills. A meta-analysis found it is reduced in clearly dangerous situations. The theory predicts these conditions.',
        patterns: [/depends|condition|context|situation/, /clear(ly)? (emergency|danger)|obvious|dangerous/, /(friends|know each other|group of friends)/, /competen|trained|skill|first aid|doctor|nurse/, /meta.?analys/, /moderat/, /not always|doesn'?t always/, /(reduce|weaken|smaller)/],
      },
      followUp: 'What would make a group MORE likely to help? Does that break the theory or refine it?',
    },
    evidenceExamples: ['Darley & Latané (1968): 85% helped when alone vs 31% when they believed four others were present.'],
    acceptableReasoning: 'Diffusion of responsibility and pluralistic ignorance explain inaction; not personality; effect depends on danger clarity, relationships, competence.',
    hints: [
      'Would the outcome change if only one person had been on the street?',
      'Each person in a crowd might assume something about the others.',
      'Psychologists have a name for how responsibility gets spread thin across a group.',
      'Bystander effect: diffusion of responsibility (someone else will help) and pluralistic ignorance (no one reacts, so it must be fine) explain the delay, not selfishness.',
    ],
    solution: {
      summary: 'Situational forces like diffusion of responsibility and pluralistic ignorance, not selfishness, often explain why crowds fail to help.',
      explanation: 'In crowds, responsibility diffuses and people read each other\'s inaction as a sign that nothing is wrong. People help far more when alone. The effect shrinks when danger is obvious or bystanders know each other.',
    },
    keywords: ['collapses', 'street', 'nobody', 'helps', 'selfish', 'people', 'crowd', 'busy'],
  },
];
